### ISSUE TITLE
interpret two component tts:fontSize as width height, not height width

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#101]
It appears that ttml2 styling attribute tts:fontSize is interpreted incorrectly. e.g., tts:fontSize="1.0em 1.5em" is interpreted as <height> <width>.

Per ttml2 spec, "if two <length> values are specified, then the first expresses the horizontal scaling and the second expresses vertical scaling."

Please confirm this behavior and if so provide a fix

**Comment by skynavga** [comment]
Fixed in 2faa84f9f76ceee267e4a7e1b91e824a2c4472dd.
