### ISSUE TITLE
add support for xml:space attribute with 'preserve' value

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#110]
Multiple whitespaces and half-width underscores are being collapsed to a single whitespace. Multiple full-width underscores are properly preserved

**Comment by skynavga** [comment]
The current behavior is correct for the 'default' value of xml:space in TTML. In order to obtain the desired behavior, it will be necessary to add support for xml:space='preserve' in TTPE and to generate this attribute in CAP2TT.

**Comment by skynavga** [comment]
See #117 for generation of attribute in CAP2TT.

**Comment by skynavga** [comment]
Addressed in a11bb0f2d31ff08a7949cef98e1ad9309d01bcd7.

**Comment by skynavga** [comment]
See also 0d12a327e64088b2b6b90703d5b4be2af836b5ef.
