### ISSUE TITLE
Cap2TT doesn't handle IDSP before timecode

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#126]
Cap2tt generates different output xml for lambdacap file using ideographic space vs regular space:

(1) Space between screen number and time-code:

Input:
０７５９	01155613/01160112	これが望みなのか？	＠斜３
０７６６ 	01162115/01162313	言わせ＠幅広［―］＠	＠斜３

Output:
<p begin="01:15:56:13" end="01:16:01:12" style="s1"><span style="s2">これが望みなのか？</span></p>
<p begin="01:16:21:15" end="01:16:23:13" style="s1"><span style="s2">言わせ<span style="s3">―</span></span></p>

(2) IDSP between screen number and time-code:

Input:
０７５９	01155613/01160112	これが望みなのか？	＠斜３
０７６６　	01162115/01162313	言わせ＠幅広［―］＠	＠斜３

Output:
<p begin="01:15:56:13" end="01:16:01:12" style="s1"><span style="s2">これが望みなのか？</span></p>
<p begin="01:15:56:13" end="01:16:01:12" style="s1"><span style="s2">０７６６　 01162115/01162313 言わせ<span style="s3">―</span></span></p>

Attaching corresponding images as well.
![idsp](https://cloud.githubusercontent.com/assets/11282730/8994817/6d498a20-36c2-11e5-8cbb-1a30f605f384.png)
![sp](https://cloud.githubusercontent.com/assets/11282730/8994816/6d47cdc0-36c2-11e5-9f4b-275f9f44ff7c.png)

**Comment by skynavga** [comment]
Not a bug. It is illegal to insert IDSP in screen number or time code.
