### ISSUE TITLE
whitespace in designation sequence content incurs parse error, resulting in loss of content

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#133]
Refer to "designation.cap" and  "designation2.cap"
Every screen in "designation.cap" and  "designation2.cap" should be italics + vertical right.

Whitespace can be ideographic or standard

**Comment by skynavga** [comment]
Fixed in ac55ca450e13b71e38b214faecd3ed72eb476855.

**Comment by skynavga** [comment]
Also added exception in case parse state error occurs, so as to provide early error notification rather than loss of content.
