### ISSUE TITLE
use of same screen number should not trigger continuation

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#135]
When a continued screen shares the same screen number as the preceding screen, the continued screen is treated as a second line to the preceding screen. It should be treated as a new screen regardless of screen numbering

Refer to "continuation.cap"

**Comment by skynavga** [comment]
Use of the same screen number as an existing screen number should behave as currently implemented, i.e., it should be treated as a continuation line. If an author wants it to mean a different screen, then a different screen number should be used. In other words, the behavior described is essentially an authoring error.
