### ISSUE TITLE
appearance of fullwidth tilde (U+FF5E) changes when comparing horizontal to vertical writing modes

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#146]
Refer to "fullwidthTilde.cap"

**Comment by skynavga** [comment]
Unable to reproduce with Oracle JDK on MacOSX. See attached images.
![ttpi000001](https://cloud.githubusercontent.com/assets/377455/10126986/73165aa4-6558-11e5-8393-36f9d2ff132a.png)
![ttpi000002](https://cloud.githubusercontent.com/assets/377455/10126988/7930c2f8-6558-11e5-8881-7ddf0d258f21.png)

**Comment by skynavga** [comment]
If by "changes appearance" you mean the full width tilde in vertical mode appears to be rotated about the horizontal axis (thus causing it to look a bit like an 'S'), then that is how it is supposed to look. See the entry for U+FF5E in [UTR #50](http://unicode.org/reports/tr50/).
