### ISSUE TITLE
when converting ＠幅広［―］＠, CAP2TT is defining tts:fontSize as "1.0em 1.5em"; should be changed to "1.5em 1.0em"

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#160]
Refer to "cap2tt.cap"

**Comment by skynavga** [comment]
unable to reproduce in ToT, which produces the following results using the default configuration with command line options `-v --output-indent cap2tt.cap`:

[test.xml.zip](https://github.com/skynav/ttt/files/74548/test.xml.zip)
