### ISSUE TITLE
when converting a vertical screen, Cap2TT is defining tts:extent as "30vh 80vh"; should be changed to "30vw 80vh"

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#161]
Refer to "cap2tt.cap"

**Comment by skynavga** [comment]
unable to reproduce in ToT, which produces the following results using the default configuration with command line options `-v --output-indent cap2tt.cap`:

[test.xml.zip](https://github.com/skynav/ttt/files/74548/test.xml.zip)

**Comment by skynavga** [comment]
note also that region extent is not defined by cap2tt, but comes from the configuration file you are using
