### ISSUE TITLE
throws transient exception InterruptedException

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#162]
Currently, TTPE seems to suppress "InterruptedException" in writeFrameEntry() {Presenter.java}. It's best to throw this and let the client or application handle the exception.

Attaching (InterruptedException.txt) which has proposed changes to achieve it.
Steps to apply it in the code.

(1) Download the patch in the root folder (ttt)
(2) Rename the file "InterruptedException.txt" to "InterruptedException.patch"
(3) git apply InterruptedException.patch
[InterruptedException.txt](https://github.com/skynav/ttt/files/83444/InterruptedException.txt)

**Comment by skynavga** [comment]
Fixed in c64ef02568d78fbade94bec084c88371e18d0b31. Avoid Thread.sleep() and thus InterruptedException. Throw IOException if BufferedInputStream.read violates contract by return zero.
