### ISSUE TITLE
transform of percentage font size results in multiple applications of percentage

### ISSUE THREAD

**Issue by skynavga** [skynav/ttt#166]
When a font size is expressed as a percentage, and that font size is inherited by a descendant, the ISD transform may apply that percentage multiple times. For example, say we have as input:

<p tts:fontSize="50%">XXX</p>

Since the ISD transform wraps XXX in an anonymous span, this translates (in ISD) to:

<p tts:fontSize="50%"><span tts:fontSize="50%">XXX</p></p>

when what we want (in ISD) is:

<p tts:fontSize="50%"><span tts:fontSize="inherit">XXX</p></p>

Since we can't resolve percentage font size until rendering time (since some inherited ancestor's font size may be based on viewport size), we need to signal that a descendant font size is explicitly inherited without repeating the percentage, which erroneously produces multiple applications of that percentage.

Note that this problem appears when transforming TTML1 content, so we would need to introduce an extension value 'inherit' in the TTML1 ISD, while we can explicitly add this to TTML2.

Alternatively, we could generate:

<p tts:fontSize="50%"><span>XXX</p></p>

i.e., not explicitly inherit an ancestor's percent based value for this property.

This problem affects both tts:fontSize and tts:lineHeight.

**Comment by skynavga** [comment]
See also #159.

**Comment by MaxEliaserAWS** [comment]
Fixed by PR #313
