### ISSUE TITLE
java.lang.NullPointerException at com.skynav.ttv.verifier.imsc.IMSC1StyleVerifier.verifyTextOutlineAttributeItem

### ISSUE THREAD

**Issue by palemieux** [skynav/ttt#184]
`java -jar c:\\bin\\ttxv\\ttt-ttxv-3.0-SNAPSHOT-jar-with-dependencies.jar --model imsc1 TextOutline001.ttml`

[TextOutline001.zip](https://github.com/skynav/ttt/files/728657/TextOutline001.zip)

**Comment by skynavga** [comment]
Fixed in 9369e6a9f56b193eb47b790976e1fd2eb7580861.
