### ISSUE TITLE
TTXV does not report spurious space in <fontFamily> value

### ISSUE THREAD

**Issue by palemieux** [skynav/ttt#187]
```
<?xml version="1.0" encoding="UTF-8"?>
<!--Modifications Copyright (c) 2017, Pierre-Anthony Lemieux (pal@palemieux.com)-->
<tt:tt xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" ttp:profile="http://www.w3.org/ns/ttml/profile/imsc1/text" xml:lang="en">
  <head>
    <metadata> 
      <ttm:title>Styling Test - FontFamily - 009</ttm:title>
      <ttm:desc>Test tts:fontFamily attribute with InexistantFont, Times New Roman value.</ttm:desc>
      <ttm:copyright>Copyright (C) 2009 W3C (MIT, ERCIM, Keio).</ttm:copyright>
    </metadata>
    
  </head>
  <body>
    <div>
      <p begin="0s" end="10s">The last words must be <span tts:fontFamily="InexistantFont, Times New Roman">using a Times New Roman font</span>.</p>
    </div>
  </body>
</tt:tt>
```

passes validation even though ` Times New Roman` starts with a space, which is not permitted by TTML1 Section 8.3.5 since the non-terminal `<familyName> | <genericFamilyName>` are explicitly separated by a comma.

**Comment by skynavga** [comment]
Just for clarification, do you mean that "TTXV does not report a spurious COMMA in <fontFamily>"? That is, the specified value ``InexistantFont, Times New Roman`` would be parsed as an unquoted-string, which would be parsed as ``identifier ( <lwsp> identifier )*``, and the appearance of COMMA should terminate the first identifier ``InexistantFont``, leaving the next token of COMMA, which does not match <lwsp>.

**Comment by skynavga** [comment]
Actually, this, i.e., <lwsp> around terms of a comma separated list, is valid, but not sufficiently documented in TTML1.
