### ISSUE TITLE
ttml1-parameter-items xsd schema error

### ISSUE THREAD

**Issue by fcartegnie** [skynav/ttt#192]
Build failure
```
[ERROR] Error while parsing schema(s).Location [ file:ttt/ttt-ttv/src/main/resources/com/skynav/ttv/xsd/ttml1/ttml1-parameter-items.xsd{65,78}].
org.xml.sax.SAXParseException; systemId: file:ttt/ttt-ttv/src/main/resources/com/skynav/ttv/xsd/ttml1/ttml1-parameter-items.xsd; lineNumber: 65; columnNumber: 78; src-resolve: Cannot resolve the name 'tt:Metadata.class' to a(n) 'group' component.

```

**Comment by skynavga** [comment]
Please run "java -version" and "mvn -version" and post results.

**Comment by fcartegnie** [comment]
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "4.14.6-200.fc26.x86_64", arch: "amd64", family: "unix"

**Comment by fcartegnie** [comment]
note that's not that single declaration. That's for every tt:Metadata.class reference

**Comment by skynavga** [comment]
Thanks. I wanted an additional data point, because I encountered the same problem yesterday (as it happens) on a different platform than I am normally using, which does not exhibit this error. I'll do some further testing to see if I can identify the problem.

On the platform I am using that does not encounter this problem, I have:

```
bash-3.2$ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
bash-3.2$ mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T13:39:06-06:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_152, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```

**Comment by skynavga** [comment]
The problem turned out to be a system dependent ordering ambiguity when compiling schema modules. The jaxb configuration has been modified to reference only the top level schema files to eliminate this ambiguity. Also updated jaxb plugin version to latest version.
