### ISSUE TITLE
IMSC 1.1 tts:shear validates without error when used in <span> elements

### ISSUE THREAD

**Issue by MsLizzie** [skynav/ttt#272]
Hi,

According to the TTML2 spec
https://www.w3.org/TR/2018/REC-ttml2-20181108/#style-attribute-shear
tts:shear should only be used on <p> elements (this is also true of tts:lineshear, however this is supported in ttml2 but not IMSC1.1)

I have received an example IMSC1.1 file, that uses tts:shear on <span> elements, but ttv validates it with no errors (both as IMSC 1.1 and TTML2)

Shouldn't the validator produce an error in this case?

Example:

```
<p region="r1" begin="1s" end="6s">
    <span tts:shear="15%">line 1</span><br/>
    <span tts:shear="20%">line 2</span>
</p>
```

**Comment by skynavga** [comment]
It is not invalid to specify a property on an element to which it does not semantically apply. See the last note under TTML2 §10.2 [1]. Note, however, that there we already have an (old) open issue (#10) to add support for warnings for such usage, which we may get around to implementing at some point in the future. In the mean time, I'm closing this issue.

[1] https://www.w3.org/TR/2018/REC-ttml2-20181108/#styling-attribute-vocabulary
