### ISSUE TITLE
Compilation Error coming when trying to build the module

### ISSUE THREAD

**Issue by aki-sud** [skynav/ttt#281]
Hi,
The following error is thrown when I run "mvn clean install" command in cmd -

[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.
1:testCompile (default-testCompile) on project ttt-ttv: Compilation failure
[ERROR]
/D:/ttt-master/ttt-ttv/src/test/java/com/skynav/ttv/w3c/ttml1/validation
/valid/ValidTestCases.java:[36,8] error while writing
com.skynav.ttv.w3c.ttml1.validation.valid.ValidTestCases: could not create parent directories

OS used- Windows 7
Maven version - 3.6.3

**Comment by skynavga** [comment]
Windows is not supported. Use MacOS or Linux platform.

**Comment by skynavga** [comment]
Note, if you have a fix and wish to propose a PR, please feel free to do so. Thanks.

**Comment by aki-sud** [comment]
Thanks and regards for your immediate support
