### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by aki-sud** [skynav/ttt#282]
Hi,
The following error is coming on compilation:-
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test
(default-test) on project ttt-ttv: There are test failures.
[ERROR]
[ERROR] Please refer to
/export/home/users/btc/shared/akhil/ttt/ttt/ttt-ttv/target/surefire-reports
for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump,
[date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to
execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test
(default-test) on project ttt-ttv: There are test failures.

Please let me know the reason as to why this is occuring and how it can be fixed.

Maven - 3.3.9
Linux 4.4.0

**Comment by skynavga** [comment]
I'm afraid these are user errors on your part, due to your unfamiliarity with Maven or your configuration. These are not compilation or test errors in TTT. I suggest you find someone with more expertise with Maven configurations that can assist you in your system setup.

**Comment by aki-sud** [comment]
Okk. I will try to resolve these errors.

Also, could you please let me know if any https url instead of a ssh url is present for updating submodules as using a ssh url keeps on giving permission denied error

[submodule "external/ttml2-tests"]
	url = git@github.com:w3c/ttml2-tests.git
[submodule "external/ttml1-tests"]
	url = git@github.com:w3c/ttml1-tests.git

**Comment by skynavga** [comment]
Follow the steps at [1] to check if your SSH configuration is correct.

[1] https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh
