### ISSUE TITLE
IMSC TTML2 Validator support

### ISSUE THREAD

**Issue by aki-sud** [skynav/ttt#283]
Hi,
Is the imsc profile for ttml2 format supported by this validator??

Spec link - https://www.w3.org/TR/2020/REC-ttml-imsc1.2-20200804/

**Comment by skynavga** [comment]
TTV supports the imsc11 model which is based on the IMSC1.1 profile [1], which is, in turn, based on TTML2. TTV does not yet, however, support the IMSC1.2 profile [2].

[1] https://www.w3.org/TR/ttml-imsc1.1/
[2] https://www.w3.org/TR/ttml-imsc1.2/

**Comment by aki-sud** [comment]
In the above spec link [1],ttp:displayAspectRatio is allowed in IMSC.

But when trying to use it in my file, following error is coming up:-

:{file:ttt/ttt-ttv/target/files/tempReport1.xml}:[2,393]:Unknown attribute in TT Parameter namespace '{http://www.w3.org/ns/ttml#parameter}displayAspectRatio' not permitted on '{http://www.w3.org/ns/ttml}tt' in imsc10.

Could you please let me know as to why this is happening??
Also, I believe IMSC1.0.1 is being used instead of imsc1.1 here. Is there any way to specify imsc1.1 to be used??

Attached is the tt attribute of my file-
<tt ttp:contentProfiles="http://www.w3.org/ns/ttml/profile/imsc1.1/text" ttp:displayAspectRatio="16 9" ttp:dropMode="nonDrop" ttp:frameRate="25" ttp:frameRateMultiplier="1 1" ttp:pixelAspectRatio="1 1" ttp:timeBase="media" tts:extent="1920px 1080px" xml:lang="en" xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling">

**Comment by skynavga** [comment]
Please attach your entire input file, input command line parameters, and output console log.
