### ISSUE TITLE
IMSC 1.1: DisplayAspectRatio gives error 

### ISSUE THREAD

**Issue by aki-sud** [skynav/ttt#284]
In the spec link https://www.w3.org/TR/ttml-imsc1.1/, **ttp:displayAspectRatio** is allowed in IMSC.

But when trying to use it in my file, following error is coming up:-

:{file:ttt/ttt-ttv/target/files/tempReport1.xml}:[2,393]:Unknown attribute in TT Parameter namespace '{http://www.w3.org/ns/ttml#parameter}displayAspectRatio' not permitted on '{http://www.w3.org/ns/ttml}tt' in imsc10.

ttp:pixelAspectRatio and ttp:contentProfiles are also giving similar errors.

Could you please let me know as to why this is happening??
Also, I believe IMSC1.0.1 is being used instead of imsc1.1 here. Is there any way to specify imsc1.1 to be used??

Attached is the tt attribute of my file-
< tt ttp:contentProfiles="http://www.w3.org/ns/ttml/profile/imsc1.1/text" ttp:displayAspectRatio="16 9" ttp:dropMode="nonDrop" ttp:frameRate="25" ttp:frameRateMultiplier="1 1" ttp:pixelAspectRatio="1 1" ttp:timeBase="media" tts:extent="1920px 1080px" xml:lang="en" xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" >

**Comment by skynavga** [comment]
Please attach your entire input file, input command line parameters, and output console log.

**Comment by aki-sud** [comment]
**Command line input and output**- 
:~ttt/ttt/ttt-ttv$ java -jar target/ttt-ttv-7.1-SNAPSHOT.jar --model imsc1 target/files/tempReport1.xml
Timed Text Verifier (TTV) [7.1-SNAPSHOT] Copyright (c) 2013-19 Skynav, Inc.
[W]:{file:/export/home/users/btc/shared/akhil/ttt/ttt/ttt-ttv/target/files/tempReport1.xml}:[2,393]:Root element '{http://www.w3.org/ns/ttml}tt' should have a '{http://www.w3.org/ns/ttml#parameter}profile' attribute, but it is missing.
[E]:{file:/export/home/users/btc/shared/akhil/ttt/ttt/ttt-ttv/target/files/tempReport1.xml}:[2,393]:Parameter value 'smpte' is prohibited on '{http://www.w3.org/ns/ttml#parameter}timeBase'.
[E]:{file:/export/home/users/btc/shared/akhil/ttt/ttt/ttt-ttv/target/files/tempReport1.xml}:[2,393]:Unknown attribute in TT Parameter namespace '{http://www.w3.org/ns/ttml#parameter}contentProfiles' not permitted on '{http://www.w3.org/ns/ttml}tt' in imsc10.
[E]:{file:/export/home/users/btc/shared/akhil/ttt/ttt/ttt-ttv/target/files/tempReport1.xml}:[2,393]:Unknown attribute in TT Parameter namespace '{http://www.w3.org/ns/ttml#parameter}displayAspectRatio' not permitted on '{http://www.w3.org/ns/ttml}tt' in imsc10.
[E]:{file:/export/home/users/btc/shared/akhil/ttt/ttt/ttt-ttv/target/files/tempReport1.xml}:[2,393]:TT Parameter attribute '{http://www.w3.org/ns/ttml#parameter}dropMode' not permitted on '{http://www.w3.org/ns/ttml}tt' in imsc10.
[E]:{file:/export/home/users/btc/shared/akhil/ttt/ttt/ttt-ttv/target/files/tempReport1.xml}:[2,393]:TT Parameter attribute '{http://www.w3.org/ns/ttml#parameter}pixelAspectRatio' not permitted on '{http://www.w3.org/ns/ttml}tt' in imsc10.

[tempReport1.txt](https://github.com/skynav/ttt/files/5620474/tempReport1.txt)

**Comment by aki-sud** [comment]
Appending file as .txt as .xml not allowed in Github.

**Comment by skynavga** [comment]
If you read the documentation at X, then you will take note of the option ``--show-models``, which when used with the current build produces the following results:

<img width="820" alt="Screen Shot 2020-12-01 at 8 25 12 AM" src="https://user-images.githubusercontent.com/377455/100753263-2bad4080-33af-11eb-9555-98bad642c311.png">

You can see from this there are three models for IMSC profiles, and that the ``imsc1`` model selects the ``imsc10``, and not the ``imsc11`` profile. So what you need to do is specify the ``imsc11`` model in your command line.

**Comment by skynavga** [comment]
The documentation I intended to reference is at https://github.com/skynav/ttt/tree/master/ttt-ttv.

**Comment by aki-sud** [comment]
okk thanks.
Also, Could you please provide me the ebutt profile link that has been used in ttv.

**Comment by skynavga** [comment]
Try google.
