### ISSUE TITLE
letterSpacing' prohibited on '{http://www.w3.org/ns/ttml}style' in imsc11 text profile

### ISSUE THREAD

**Issue by fengliuxiaoxin** [skynav/ttt#309]
I'm trying to convert ttml to svg.
but when I use "tts:letterSpacing"  in style Attribute, verification failed.
It notes that,
Attribute '{http://www.w3.org/ns/ttml#styling}letterSpacing' prohibited on '{http://www.w3.org/ns/ttml}style' in imsc11 text profile.
I dont how to fix this, is there a substitutable attribute?
thanks so much if anyone can help.

**Comment by nigelmegitt** [comment]
The TTML2 [`#letterSpacing`](https://www.w3.org/TR/ttml2/#feature-letterSpacing) feature is not supported in IMSC so the tool is correct. However if you have a use case for this feature please could you raise it as an issue for IMSC at https://github.com/w3c/imsc/issues/ ?

CC @palemieux

**Comment by fengliuxiaoxin** [comment]
您好，我会在阅读完该邮件后第一时间回复您。

**Comment by fengliuxiaoxin** [comment]
Sure, thank you so much!

**Comment by skynavga** [comment]
Question answered. Closing.
