### ISSUE TITLE
Possible typo in ttt-cap2tt/src/main/resources/com/skynav/cap2tt/app/messages.properties

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#31]
around line number 57, we see the following:

w.002           = Header bad field count, got {0}, expected {1}.
w.002           = fieldCount
w.002           = minFieldCount

Perhaps, the following is desired:
w.002           = Header bad field count, got {0}, expected {1}.
#w.002.0           = fieldCount
#w.002.1           = minFieldCount

**Comment by skynavga** [comment]
Fixed in fb04e2097f677fd35c68d43261772056879553a1.
