### ISSUE TITLE
I set a style attribute tts:fontSize="70%" instead of "100%", the fonts would overlap. 

### ISSUE THREAD

**Issue by fengliuxiaoxin** [skynav/ttt#310]
I found a problem:
I set a style attribute tts:fontSize="70%" instead of "100%", the fonts would overlap.  like the following pic:
![ttpi000001](https://user-images.githubusercontent.com/30992689/194694244-6df9586e-a3ca-434c-a0ab-4f8d26ca83bd.png)
How to set the fonts size 70% and make them not overlap. I didn't find this piece of code to fix it.
Would appreciate it if anyone could do me a fovar.

**Comment by fengliuxiaoxin** [comment]
Just like this. 
[ttml_chn_eng.ttml.txt](https://github.com/skynav/ttt/files/9740661/ttml_chn_eng.ttml.txt)
Thanks for your help again.

**Comment by nigelmegitt** [comment]
As a reference point, I cannot reproduce the issue using the CSS-based renderer at https://www.sandflow.com/imsc1_1/index.html

**Comment by fengliuxiaoxin** [comment]
thank so much,  so grateful for your help.
I'll try to solve this again.
really really thanks.
