### ISSUE TITLE
message strings in cap2tt messages.properties do not appear to be picked up by Reporter

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#46]
When message strings in 'messages.properties' file are altered from the corresponding strings in Converter.java, they get picked up by stdout. It does not seem like they are getting picked up by the Reporter instance hooked to the Converter - it seems to use the message string used in Converter.java. Would it be possible to confirm this observation and provide a fix pending that?

**Comment by skynavga** [comment]
Unable to reproduce. Added new test case in 089d7cfe4afab8eb5660a542ba05a98fe9dee416 which verifies external reporter and mapped bundle message. No problem indicated.

**Comment by shimada-development** [comment]
Hi Glenn,

do you mind taking a look at this again? i retried this with the latest
(beta) drop and it does not seem to be working.

I also noticed from your commit (
https://github.com/skynav/ttt/commit/089d7cfe4afab8eb5660a542ba05a98fe9dee416)
that the testcase does not cover the concern i had raised.

Specifically, in the commit, you have identical message strings for w.011
in messages.properties (around line 83) as well as in Converter.java
(around line 1695). In that case, the problem cannot be illustrated. what i
am seeing is that when Converter.java and messages.properties have
different strings for the same key, an externally instantiated Reporter
records the string in Converter.java (My understanding was that
Converter.java provides the default that will be overridden by
messages.properties).

Thanks,
Rohit



On Tue, May 5, 2015 at 1:56 PM, Glenn Adams <notifications@github.com>
wrote:

> Unable to reproduce. Added new test case in 089d7cf
> <https://github.com/skynav/ttt/commit/089d7cfe4afab8eb5660a542ba05a98fe9dee416>
> which verifies external reporter and mapped bundle message. No problem
> indicated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skynav/ttt/issues/46#issuecomment-99219448>.
>
> --
> You received this message because you are subscribed to the Google Groups
> "Shimada Development" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to shimada-development+unsubscribe@netflix.com.
> To post to this group, send email to shimada-development@netflix.com.
> To view this discussion on the web visit
> https://groups.google.com/a/netflix.com/d/msgid/shimada-development/skynav/ttt/issues/46/99219448%40github.com
> <https://groups.google.com/a/netflix.com/d/msgid/shimada-development/skynav/ttt/issues/46/99219448%40github.com?utm_medium=email&utm_source=footer>
> .
>



-- 



Best regards,
Rohit Puri
(rpuri@netflix.com)

**Comment by skynavga** [comment]
I verified manually by editing messages.properties, then executed cap2tt standalone against an empty input file in order to produce warning w.011. I did this in two ways: (1) from maven target/classes and (2) from maven jar artifacts only. In both cases, it used my manually edited message, and not the default in Converter.

My speculation is that on your configuration it isn't loading the properties bundle, and so is using the default message in Converter. In Converter, the bundle is loaded by getResourceBundle() and passed as the third argument to reporter.open(). If you are using an external reporter, then you need to either make sure it isn't already open, or that you open it in your code providing the bundle you desire. If you don't open it, then it will be opened by Converter.setReporter(Reporter reporter, PrintWriter reporterOutput, String reporterOutputEncoding, boolean reporterIncludeSource, boolean closeOldReporter).

If you haven't opened it already and you are letting Converter.getResourceBundle() be used to obtain the bundle, then perhaps it is a locale issue, since we have:

<pre>
private ResourceBundle getReporterBundle() {
  try {
    return ResourceBundle.getBundle("com/skynav/cap2tt/app/messages", Locale.getDefault());
  } catch (MissingResourceException e) {
    return null;
  }
}
</pre>

**Comment by shimada-development** [comment]
thanks for the tip - i will give it a shot soon.

Best regards,
Rohit


On Tue, May 5, 2015 at 7:24 PM, Glenn Adams <notifications@github.com>
wrote:

> I verified manually by editing messages.properties, then executed cap2tt
> standalone against an empty input file in order to produce warning w.011. I
> did this in two ways: (1) from maven target/classes and (2) from maven jar
> artifacts only. In both cases, it used my manually edited message, and not
> the default in Converter.
>
> My speculation is that on your configuration it isn't loading the
> properties bundle, and so is using the default message in Converter. In
> Converter, the bundle is loaded by getResourceBundle() and passed as the
> third argument to reporter.open(). If you are using an external reporter,
> then you need to either make sure it isn't already open, or that you open
> it in your code providing the bundle you desire. If you don't open it, then
> it will be opened by Converter.setReporter(Reporter reporter, PrintWriter
> reporterOutput, String reporterOutputEncoding, boolean
> reporterIncludeSource, boolean closeOldReporter).
>
> If you haven't opened it already and you are letting
> Converter.getResourceBundle() be used to obtain the bundle, then perhaps it
> is a locale issue, since we have:
>
> private ResourceBundle getReporterBundle() {
>   try {
>     return ResourceBundle.getBundle("com/skynav/cap2tt/app/messages", Locale.getDefault());
>   } catch (MissingResourceException e) {
>     return null;
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skynav/ttt/issues/46#issuecomment-99292918>.
>
> --
> You received this message because you are subscribed to the Google Groups
> "Shimada Development" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to shimada-development+unsubscribe@netflix.com.
> To post to this group, send email to shimada-development@netflix.com.
> To view this discussion on the web visit
> https://groups.google.com/a/netflix.com/d/msgid/shimada-development/skynav/ttt/issues/46/99292918%40github.com
> <https://groups.google.com/a/netflix.com/d/msgid/shimada-development/skynav/ttt/issues/46/99292918%40github.com?utm_medium=email&utm_source=footer>
> .
>



-- 



Best regards,
Rohit Puri
(rpuri@netflix.com)
