### ISSUE TITLE
generation of isd output from ttpe seems broken

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#48]
When we use the following command line options for Presenter:

argList.add("--output-retain-isd");
argList.add("--output-pattern-isd");
argList.add(".isd");

only one isd file with name ".isd" is generated. It appears that all the output isds are written to this filename

**Comment by skynavga** [comment]
Not a bug. You must specify a pattern string that is compatible with the following usage:

<pre>
MessageFormat.format(outputPatternISD, ++outputFileSequenceISD);
</pre>

For example, ```isdi{0,number,000000}.xml```.
